### ISSUE TITLE
Bokeh and HoloViews datashader support to-do list

### ISSUE THREAD

**Issue by jbednar** [pyviz/datashader#669]
Datashader can make complete images on its own, but it's a lot more powerful when combined with an external plotting program like Bokeh, Plotly, or Matplotlib that can draw axes, add additional types of data as overlays or adjacent plots, provide interactivity such as hovering or click detection, add colorbars and color keys, etc.  But these programs don't typically provide the special colormapping and related features of datashader, so there's still a long to-do list of tasks across libraries that would improve integration. This issue focuses on issues for the Bokeh backend of Holoviews, most of which will require adding functionality to Bokeh that would then be exposed in HoloViews if needed.

From [datashade_vs_rasterize](https://anaconda.org/jbednar/datashade_vs_rasterize/notebook):

- [ ] [Shading normalization other than linear, log](http://datashader.org/api.html#datashader.transfer_functions.shade) (hist_eq, cbrt, custom)
- [ ] [bokeh #8061 LogTicker broken for colormaps that include zero](https://github.com/bokeh/bokeh/issues/8061#issuecomment-403564997)
- [ ] [Spreading](http://holoviews.org/user_guide/Large_Data.html#Spreading) (spread, dynspread)
- [ ] [Stacking](http://holoviews.org/Reference_Manual/holoviews.operation.html#holoviews.operation.datashader.stack) (add, over, saturate, source)
- [ ] [Shading value as alpha](http://datashader.org/api.html#datashader.transfer_functions.shade) (passing a single color to `cmap`)
- [ ] [Shading categories as mixed colors](http://datashader.org/api.html#datashader.transfer_functions.shade) (with `aggregator=count_cat()`)

Once the above is done, there are various Datashader issues that can be closed, such as requests for hover information, legends, colorbars, and interactivity (#126, #127, #136, #251).
